apiVersion: v1
kind: Service
metadata:
  name: {{ include "periplus.fullname" . }}
  labels:
    {{- include "periplus.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "periplus.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
{{- if .Values.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "periplus.fullname" . }}
  labels:
    {{- include "periplus.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "periplus.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
{{- end }}
